### ISSUE TITLE
Exception ES3InvalidArgument with message 'The continuation token provided is incorrect'

### ISSUE THREAD

**Issue by joydeep-das5** [appercept/aws-sdk-delphi-samples#1]
Hi, 
I am trying to get a list of all objects ( more than 1000 items) from a bucket. When I am trying to call the "S3Client.ListObjectsV2" for the 2nd time using the "v2Response.NextContinuationToken" it gives the above error.

I am getting the same error when trying the code from https://github.com/appercept/aws-sdk-delphi-samples/tree/main/S3Explorer. 

I have created a console application and tried to reproduce the above error by specifying "MaxKeys" = 2. I don't actually need thousands of items in the bucket. The issue can be reproduced if there are more than two items in the bucket. I hope this will help to investigate the issue further.

[S3Viewer.zip](https://github.com/appercept/aws-sdk-delphi-samples/files/13956259/S3Viewer.zip)

![image](https://github.com/appercept/aws-sdk-delphi-samples/assets/151124591/a126c3b5-19ce-4c55-af3c-748b3ead12fd)

 - OS: Windows 11 Pro x64
 - Delphi Version 11 update 3
 - Appercept AWS SDK Version  0.12.0

Thanks !

**Comment by rhatherall** [comment]
Thank you for reporting this @joydeep-das5 . I have identified the issue, and a fix will be released shortly. Keep an eye on GetIt for updates. This issue was caused when providing a workaround for the broken `TURI` implementation in Delphi 12. It's only the latest version (0.20.0) that is affected. I'm sorry for any inconvenience.

**Comment by joydeep-das5** [comment]
Thanks, @rhatherall, for a quick fix. Waiting for the update :)

**Comment by rhatherall** [comment]
BTW @joydeep-das5 , if the GetIt outage goes on for much longer, ping me a message at support@appercept.com, and we'll see if we can sort an update another way.
